repos:
  - repo: https:/github.com/astral-sh/uv-pre-commit
    rev: 0.5.24
    hooks:
      - id: uv-lock
      - id: uv-export
      entry: uv
      args: [export, -o, requirements.txt, -no-hashes, -q]
      always_run: true